language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -e .
env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk
script:
  - python test/test_menu.py